window.TENANTS = [
  { name: "Adult and Child Optical", lease: "Fixed Rent", category: "Health & Wellness" },
  { name: "Cebuana Lhuillier", lease: "Fixed Rent", category: "Banking & Finance", logo: "images/tenants/cebuana_lhuillier_logo.jpg" },
  { name: "Core Pacific", lease: "Fixed Rent", category: "Services", logo: "images/tenants/core_pacific_logo.jpg" },
  { name: "RD Pawnshop", lease: "Fixed Rent", category: "Banking & Finance", logo: "images/tenants/rd_pawnshop_logo.png" },
  { name: "Robinson's Supermarket", lease: "Fixed Rent", category: "Retail & Essentials", logo: "images/tenants/robinson_supermarket_logo.jpg" },
  { name: "Security Bank", lease: "Fixed Rent", category: "Banking & Finance", logo: "images/tenants/security_bank_logo.png" },
  { name: "Southstar Drugstore", lease: "Fixed Rent", category: "Health & Wellness", logo: "images/tenants/southstar_drug_store_logo.png" },
  { name: "Wondersnails", lease: "Fixed Rent", category: "Health & Wellness", logo: "images/tenants/wonder_nails_logo.jpg" },
  { name: "Executive Optical", lease: "Fixed Rent", category: "Health & Wellness", logo: "images/tenants/executive_optical_logo.png" },
  { name: "E&E Takuyaki", lease: "Fixed Rent", category: "Dining & Food", logo: "images/tenants/e_e_takuyaki_logo.jpg" },
  { name: "Goldilocks", lease: "Fixed Rent", category: "Dining & Food", logo: "images/tenants/goldilocks_logo.jpg" },
  { name: "Leylam", lease: "Fixed Rent", category: "Dining & Food", logo: "images/tenants/leylam_logo.jpg" },
  { name: "Master Siomai", lease: "Fixed Rent", category: "Dining & Food", logo: "images/tenants/master_siomai_logo.png" },
  { name: "My Choice Ice Cream", lease: "Fixed Rent", category: "Dining & Food", logo: "images/tenants/my_choice_ice_cream_logo.png" },
  { name: "Miguelitos Ice Cream", lease: "Fixed Rent", category: "Dining & Food", logo: "images/tenants/miguelitos_ice_cream_logo.jpg" },
  { name: "Painitan Central", lease: "Fixed Rent", category: "Dining & Food", logo: "images/tenants/painitan_central_logo.jpg" },
  { name: "The Lemon Co. / DJ Leminade Juice Station", lease: "Fixed Rent", category: "Dining & Food", logo: "images/tenants/the_lemon_co_logo.jpg" },
  { name: "Thirsty", lease: "Fixed Rent", category: "Dining & Food", logo: "images/tenants/thirsty_logo.jpg" },
  { name: "Tiktilaok", lease: "Fixed Rent", category: "Dining & Food", logo: "images/tenants/tiktilaok_logo.jpg" },
  { name: "Mama's Choice", lease: "Fixed Rent", category: "Retail & Essentials", logo: "images/tenants/mama's_choice_logo.jpg" },
  { name: "Cebu Tasty Lechon", lease: "Fixed Rent", category: "Dining & Food", logo: "images/tenants/cebu's_tasty_letchon_logo.jpg" },
  { name: "Famous Belgian Waffle", lease: "Fixed Rent", category: "Dining & Food", logo: "images/tenants/famous_belgian_waffles_logo.png" },
  { name: "CEF Travel and Tours", lease: "Fixed Rent", category: "Services", logo: "images/tenants/cef_logo.png" },
  { name: "Joaquin Grilling Station", lease: "Fixed Rent", category: "Dining & Food", logo: "images/tenants/joaquin_logo.jpg" },
  { name: "Turon Express", lease: "Fixed Rent", category: "Dining & Food", logo: "images/tenants/turon_express_logo.png" },
  { name: "Shawarma Shack", lease: "Fixed Rent", category: "Dining & Food", logo: "images/tenants/shawarma_shack_logo.png" },
  { name: "DITO Tel. Corp.", lease: "Fixed Rent", category: "Gadgets & Tech", logo: "images/tenants/dito_logo.png" },
  { name: "Globe Telecom (Booster)", lease: "Fixed Rent", category: "Gadgets & Tech", logo: "images/tenants/globe_logo.png" },
  { name: "PHCCI ATM", lease: "Fixed Rent", category: "Banking & Finance", logo: "images/tenants/phcci_logo.png" },
  { name: "PS Bank ATM", lease: "Fixed Rent", category: "Banking & Finance", logo: "images/tenants/ps_bank_logo.png" },
  { name: "UCPB ATM / Landbank", lease: "Fixed Rent", category: "Banking & Finance", logo: "images/tenants/ucpb_landbank_logo.jpg" },
  { name: "Xoooom Auto Spa", lease: "Fixed Rent", category: "Services" },
  { name: "Mr. Potato", lease: "Fixed Rent", category: "Dining & Food", logo: "images/tenants/mr_potato_logo.jpg" },
  { name: "Hearts & Hands Massage", lease: "Fixed Rent", category: "Health & Wellness", logo: "images/tenants/hearts_and_hands_logo.jpg" },
  { name: "National Bookstore", lease: "Fixed Rent", category: "Retail & Essentials", logo: "images/tenants/national_bookstore_logo.png" },
  { name: "No Strips Waxing Salon", lease: "Fixed Rent", category: "Health & Wellness", logo: "images/tenants/no_strips_logo.png" },
  { name: "Orochina", lease: "Fixed Rent", category: "Retail & Essentials" },
  { name: "Watch Republic", lease: "Fixed Rent", category: "Retail & Essentials", logo: "images/tenants/watch_republic_logo.jpg" },
  { name: "A Little Tea", lease: "Fixed Rent", category: "Dining & Food", logo: "images/tenants/a_little_tea_logo.png" },
  { name: "Salon de Rose", lease: "Fixed Rent", category: "Health & Wellness", logo: "images/tenants/salon_de_rose_logo.jpg" },
  { name: "TUF", lease: "Fixed Rent", category: "Retail & Essentials", logo: "images/tenants/tuf_logo.png" },
  { name: "RELX", lease: "Fixed Rent", category: "Retail & Essentials", logo: "images/tenants/relx_logo.png" },
  { name: "Aya's Cellphone & Acc", lease: "Fixed Rent", category: "Gadgets & Tech" },
  { name: "Cellnote Gadget", lease: "Fixed Rent", category: "Gadgets & Tech" },
  { name: "Ding's iPhone", lease: "Fixed Rent", category: "Gadgets & Tech" },
  { name: "GB08", lease: "Fixed Rent", category: "Gadgets & Tech" },
  { name: "4J Gadget", lease: "Fixed Rent", category: "Gadgets & Tech" },
  { name: "GB Repair", lease: "Fixed Rent", category: "Gadgets & Tech" },
  { name: "Shukey", lease: "Fixed Rent", category: "Retail & Essentials" },
  { name: "Techboy", lease: "Fixed Rent", category: "Gadgets & Tech" },
  { name: "Vivo Kiosk", lease: "Fixed Rent", category: "Gadgets & Tech" },
  { name: "World of Adventures", lease: "Fixed Rent", category: "Entertainment" },
  { name: "DBCI", lease: "Fixed Rent", category: "Services" },
  { name: "DK & Choco Gadget", lease: "Fixed Rent", category: "Gadgets & Tech" },
  { name: "Mizelle Gadget & Accessories Shop", lease: "Fixed Rent", category: "Gadgets & Tech" },
  { name: "CRL Gadgets PH", lease: "Fixed Rent", category: "Gadgets & Tech" },
  { name: "Audionet", lease: "Fixed Rent", category: "Gadgets & Tech" },
  { name: "Allytac Printing", lease: "Fixed Rent", category: "Services" },
  { name: "PHCCI", lease: "Fixed Rent", category: "Banking & Finance", logo: "images/tenants/phcci_logo.png" },
  { name: "Tropique", lease: "Fixed Rent", category: "Retail & Essentials" },
  { name: "Bono Optical", lease: "Fixed Rent", category: "Health & Wellness" },
  { name: "Nast Fitness", lease: "Fixed Rent", category: "Health & Wellness", logo: "images/tenants/nast_fitness_logo.png" },
  { name: "ICM Cinema", lease: "Fixed Rent", category: "Entertainment" },
  { name: "Royal Spoon Inc. (Jollibee)", lease: "Sales Rent", category: "Dining & Food", logo: "images/tenants/jollibee_logo.png" },
  { name: "Kuya J", lease: "Sales Rent", category: "Dining & Food", logo: "images/tenants/kuya_j_logo.jpg" },
  { name: "Timezone", lease: "Sales Rent", category: "Entertainment", logo: "images/tenants/timezone_logo.jpg" },
  { name: "Timezone - VR", lease: "Sales Rent", category: "Entertainment", logo: "images/tenants/timezone_logo.jpg" },
  { name: "McDonald's", lease: "Sales Rent", category: "Dining & Food", logo: "images/tenants/mcdo_logo.png" },
  { name: "Watsons", lease: "Sales Rent", category: "Health & Wellness", logo: "images/tenants/watsons_logo.png" },
  { name: "Freelife", lease: "Sales Rent", category: "Retail & Essentials", logo: "images/tenants/free_life_logo.jpg" },
  { name: "Orange Brutus", lease: "Sales Rent", category: "Dining & Food", logo: "images/tenants/orange_brutus_logo.jpg" },
  { name: "ZUS Coffee", lease: "Sales Rent", category: "Dining & Food", logo: "images/tenants/zus_coffee_logo.png" },
  { name: "Pan de Manila", lease: "Sales Rent", category: "Dining & Food", logo: "images/tenants/pan_de_manila_logo.png" },
  { name: "Sachi Best Ramen Corp", lease: "Sales Rent", category: "Dining & Food", logo: "images/tenants/sachi_logo.jpg" },
  { name: "Ribshack", lease: "Sales Rent", category: "Dining & Food", logo: "images/tenants/ribshack_logo.jpg" },
  { name: "Dunkin Donuts", lease: "Sales Rent", category: "Dining & Food", logo: "images/tenants/dunkin_donuts_logo.png" },
  { name: "Choobi Choobi", lease: "Sales Rent", category: "Dining & Food", logo: "images/tenants/choobi_logo.jpg" },
  { name: "Ace Hardware", lease: "Sales Rent", category: "Retail & Essentials", logo: "images/tenants/ace_hardware_logo.jpg" },
  { name: "Brand Central", lease: "Sales Rent", category: "Retail & Essentials" },
  { name: "Cookpub", lease: "Sales Rent", category: "Dining & Food", logo: "images/tenants/cookpub_logo.jpg" },
  { name: "Mr. DIY", lease: "Sales Rent", category: "Retail & Essentials" },
  { name: "Penshoppe", lease: "Sales Rent", category: "Retail & Essentials", logo: "images/tenants/penshoppe_logo.jpg" },
  { name: "Penshoppe Accessories", lease: "Sales Rent", category: "Retail & Essentials", logo: "images/tenants/penshoppe_accessories_logo.png" },
  { name: "PHO19", lease: "Sales Rent", category: "Dining & Food", logo: "images/tenants/pho19_logo.jpg" },
  { name: "Regatta", lease: "Sales Rent", category: "Retail & Essentials", logo: "images/tenants/regatta_logo.jpg" },
  { name: "Yamato Restaurant", lease: "Sales Rent", category: "Dining & Food", logo: "images/tenants/yamato_logo.jpg" },
  { name: "Turks", lease: "Sales Rent", category: "Dining & Food", logo: "images/tenants/turks_logo.jpg" },
  { name: "Kids Paradise", lease: "Sales Rent", category: "Entertainment", logo: "images/tenants/kids_paradise_logo.jpg" },
  { name: "LTO", lease: "Sales Rent", category: "Government & Offices" },
  { name: "BMEAD", lease: "Sales Rent", category: "Government & Offices" },
  { name: "NBI", lease: "Sales Rent", category: "Government & Offices" },
  { name: "Vibe", lease: "Sales Rent", category: "Entertainment", logo: "images/tenants/vibe_logo.jpg" },
  { name: "Taters", lease: "Sales Rent", category: "Dining & Food" },
  { name: "Gurlz Fav Fashion Shop", lease: "Exhibit Long Term", category: "Retail & Essentials" },
  { name: "Amerys", lease: "Exhibit Long Term", category: "Retail & Essentials" },
  { name: "Chona Feng Shui", lease: "Exhibit Long Term", category: "Retail & Essentials" },
  { name: "Dino Rides", lease: "Exhibit Long Term", category: "Entertainment" },
  { name: "Don Macchiato", lease: "Exhibit Long Term", category: "Dining & Food" },
  { name: "FNJ", lease: "Exhibit Long Term", category: "Retail & Essentials" },
  { name: "Hygea Wellness and Spa", lease: "Exhibit Long Term", category: "Health & Wellness" },
  { name: "Lezel Sandals", lease: "Exhibit Long Term", category: "Retail & Essentials" },
  { name: "Paglaum", lease: "Exhibit Long Term", category: "Retail & Essentials" },
  { name: "Sugardolls", lease: "Exhibit Long Term", category: "Dining & Food" },
  { name: "Tasty Bites", lease: "Exhibit Long Term", category: "Dining & Food" },
  { name: "VSPA", lease: "Exhibit Long Term", category: "Health & Wellness" },
];

const TENANT_LOCATIONS = {
  "Adult and Child Optical": "Ground Floor - Beauty & Wellness",
  "Cebuana Lhuillier": "Ground Floor - Non-Banking",
  "Core Pacific": "Ground Floor - Money Exchange",
  "RD Pawnshop": "Ground Floor - Non-Banking",
  "Robinson's Supermarket": "Ground Floor - Supermarket",
  "Security Bank": "Ground Floor - Banking & Finance",
  "Southstar Drugstore": "Ground Floor - Beauty & Wellness",
  Wondersnails: "Ground Floor - Beauty & Wellness",
  "Executive Optical": "Ground Floor - Beauty & Wellness",
  "E&E Takuyaki": "Ground Floor - Food Option",
  Goldilocks: "Ground Floor - Food Option",
  Leylam: "Ground Floor - Food Option",
  "Master Siomai": "Ground Floor - Food Option",
  "My Choice Ice Cream": "Ground Floor - Food Option",
  "Miguelitos Ice Cream": "Ground Floor - Food Option",
  "Painitan Central": "Ground Floor - Food Option",
  "The Lemon Co. / DJ Leminade Juice Station": "Ground Floor - Food Option",
  Thirsty: "Ground Floor - Food Option",
  Tiktilaok: "Ground Floor - Food Option",
  "Mama's Choice": "Ground Floor - Food Option",
  "Cebu Tasty Lechon": "Ground Floor - Food Option",
  "Famous Belgian Waffle": "Ground Floor - Food Option",
  "CEF Travel and Tours": "Third Floor - Services",
  "Joaquin Grilling Station": "Ground Floor - Food Option",
  "Turon Express": "Ground Floor - Food Option",
  "Shawarma Shack": "Ground Floor - Food Option",
  "DITO Tel. Corp.": "Third Floor - Tech Hub",
  "Globe Telecom (Booster)": "Third Floor - Tech Hub",
  "PHCCI ATM": "Ground Floor - ATMS",
  "PS Bank ATM": "Ground Floor - ATMS",
  "UCPB ATM / Landbank": "Ground Floor - ATMS",
  "Xoooom Auto Spa": "Basement 1 - Services",
  "Mr. Potato": "Ground Floor - Food Option",
  "Hearts & Hands Massage": "Second Floor - Services",
  "National Bookstore": "Second Floor - Hardware & Necessities",
  "No Strips Waxing Salon": "Second Floor - Beauty & Wellness",
  Orochina: "Second Floor - Fashion",
  "Watch Republic": "Second Floor - Fashion",
  "A Little Tea": "Second Floor - Food Option",
  "Salon de Rose": "Ground Floor - Beauty & Wellness",
  TUF: "Second Floor - Beauty & Wellness",
  RELX: "Second Floor - Services",
  "Aya's Cellphone & Acc": "Third Floor - Tech Hub",
  "Cellnote Gadget": "Third Floor - Tech Hub",
  "Ding's iPhone": "Third Floor - Tech Hub",
  GB08: "Third Floor - Tech Hub",
  "4J Gadget": "Third Floor - Tech Hub",
  "GB Repair": "Third Floor - Tech Hub",
  Shukey: "Third Floor - Services",
  Techboy: "Third Floor - Tech Hub",
  "Vivo Kiosk": "Third Floor - Tech Hub",
  "World of Adventures": "Second Floor - Services",
  DBCI: "Third Floor - Tech Hub",
  "DK & Choco Gadget": "Third Floor - Tech Hub",
  "Mizelle Gadget & Accessories Shop": "Third Floor - Tech Hub",
  "CRL Gadgets PH": "Third Floor - Tech Hub",
  Audionet: "Third Floor - Tech Hub",
  "Allytac Printing": "Third Floor - Services",
  PHCCI: "Third Floor - Government Services",
  Tropique: "Third Floor - Beauty & Wellness",
  "Bono Optical": "Third Floor - Beauty & Wellness",
  "Nast Fitness": "Fourth Floor - Fitness",
  "ICM Cinema": "Fourth Floor - Recreation & Entertainment",
  "Royal Spoon Inc. (Jollibee)": "Ground Floor - Food Option",
  "Kuya J": "Ground Floor - Food Option",
  Timezone: "Second Floor - Games & Fun",
  "Timezone - VR": "Second Floor - Games & Fun",
  "McDonald's": "Ground Floor - Food Option",
  Watsons: "Ground Floor - Beauty & Wellness",
  Freelife: "Ground Floor - Beauty & Wellness",
  "Orange Brutus": "Ground Floor - Food Option",
  "ZUS Coffee": "Ground Floor - Food Option",
  "Pan de Manila": "Ground Floor - Food Option",
  "Sachi Best Ramen Corp": "Ground Floor - Food Option",
  Ribshack: "Ground Floor - Food Option",
  "Dunkin Donuts": "Ground Floor - Food Option",
  "Choobi Choobi": "Ground Floor - Food Option",
  "Ace Hardware": "Second Floor - Hardware & Necessities",
  "Brand Central": "Second Floor - Fashion",
  Cookpub: "Second Floor - Food Option",
  "Mr. DIY": "Second Floor - Hardware & Necessities",
  Penshoppe: "Second Floor - Fashion",
  "Penshoppe Accessories": "Second Floor - Fashion",
  PHO19: "Second Floor - Food Option",
  Regatta: "Second Floor - Fashion",
  "Yamato Restaurant": "Second Floor - Food Option",
  Turks: "Ground Floor - Food Option",
  "Kids Paradise": "Third Floor - Games and Fun",
  LTO: "Third Floor - Government Services",
  BMEAD: "Third Floor - Government Services",
  NBI: "Third Floor - Government Services",
  Vibe: "Fourth Floor - Food Options",
  Taters: "Fourth Floor - Food Options",
  "Gurlz Fav Fashion Shop": "Mall Exhibit Area",
  Amerys: "Mall Exhibit Area",
  "Chona Feng Shui": "Mall Exhibit Area",
  "Dino Rides": "Mall Exhibit Area",
  "Don Macchiato": "Ground Floor - Food Option",
  FNJ: "Mall Exhibit Area",
  "Hygea Wellness and Spa": "Mall Exhibit Area",
  "Lezel Sandals": "Mall Exhibit Area",
  Paglaum: "Mall Exhibit Area",
  Sugardolls: "Ground Floor - Beauty & Wellness",
  "Tasty Bites": "Mall Exhibit Area",
  VSPA: "Mall Exhibit Area",
};

window.TENANTS = window.TENANTS.map((tenant) => ({
  ...tenant,
  location: TENANT_LOCATIONS[tenant.name] || "Location to be confirmed",
}));
