import { useEffect } from "react";
import { useLocation } from "react-router-dom";
import { assetUrl } from "../../config/site";
import { useSettings } from "../../hooks/useContent";

const pageNames={"/":"Home","/mall":"Mall","/directory":"Directory","/leasing":"Leasing","/events":"Events & Promos","/about":"About Us","/services":"Services","/inquire":"Contact Us"};
function meta(name,content,property=false){if(!content)return;const key=property?"property":"name";let tag=document.head.querySelector(`meta[${key}="${name}"]`);if(!tag){tag=document.createElement("meta");tag.setAttribute(key,name);document.head.appendChild(tag)}tag.setAttribute("content",content)}

export function Seo(){const settings=useSettings(),location=useLocation();useEffect(()=>{const page=pageNames[location.pathname]||"Island Central Mactan",base=settings["seo.default_title"]||"Island Central Mactan",title=location.pathname==="/"?base:`${page} | ${base}`,description=settings[`seo.${location.pathname==="/"?"home":location.pathname.slice(1)}_description`]||settings["seo.default_description"]||"Explore Island Central Mactan.";document.title=title;meta("description",description);meta("og:title",title,true);meta("og:description",description,true);meta("og:type","website",true);meta("og:url",window.location.href,true);meta("og:image",new URL(assetUrl(settings["seo.og_image"]||"images/general_images/icm.webp"),window.location.origin).href,true);meta("twitter:card","summary_large_image");let canonical=document.head.querySelector('link[rel="canonical"]');if(!canonical){canonical=document.createElement("link");canonical.rel="canonical";document.head.appendChild(canonical)}canonical.href=window.location.href.split(/[?#]/)[0];let schema=document.head.querySelector('#icm-structured-data');if(!schema){schema=document.createElement("script");schema.id="icm-structured-data";schema.type="application/ld+json";document.head.appendChild(schema)}schema.textContent=JSON.stringify({"@context":"https://schema.org","@type":"ShoppingCenter",name:base,description:settings["seo.default_description"],url:window.location.origin,image:new URL(assetUrl(settings["seo.og_image"]||"images/general_images/icm.webp"),window.location.origin).href,address:{"@type":"PostalAddress",addressLocality:"Lapu-Lapu City",addressRegion:"Cebu",addressCountry:"PH"},sameAs:[settings["social.facebook"],settings["social.instagram"],settings["social.tiktok"]].filter(Boolean)})},[location.pathname,settings]);return null}
