import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { useContent, useSettings } from "../../hooks/useContent";
import { assetUrl } from "../../config/site";

export const Loading = () => <div className="loading">Loading content&hellip;</div>;
export function PageHero({ title, text, variant="mall", eyebrow="Island Central Mactan", backgroundUrl, children }) { const style=backgroundUrl?{backgroundImage:`linear-gradient(90deg,rgba(3,29,35,.9),rgba(3,29,35,.3)),url("${assetUrl(backgroundUrl)}")`}:undefined;return <section className={`page-hero page-hero-${variant}`} style={style}><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p>{text}</p>{children}</div></section>; }
export function Feature({ icon,title,text,to }) { return <article className="feature"><i>{icon}</i><h3>{title}</h3><p>{text}</p><Link to={to}>Explore &rarr;</Link></article>; }
function tenantImage(value){if(!value)return "";try{const parsed=JSON.parse(value);return Array.isArray(parsed)?parsed[0]||"":parsed}catch{return value}}
export function TenantGrid({ tenants,onSelect }) { return <div className="card-grid">{tenants.map(tenant => {const name=tenant.trade_name||tenant.name,image=tenantImage(tenant.picture_of_branches),content=<><div className="tenant-logo-stage">{image?<img src={assetUrl(image)} alt={`${name} logo`} loading="lazy" decoding="async"/>:<div className="logo-fallback">{name?.[0]||"?"}</div>}</div><div>{tenant.industry_name&&<small className="tenant-type-badge">{tenant.industry_name}</small>}<span>{tenant.company_address||"Island Central Mactan"}</span><h3>{name}</h3>{onSelect&&<small className="tenant-view-details">View details &rarr;</small>}</div></>;return <article className={`tenant${onSelect?" tenant-clickable":""}`} key={name}>{onSelect?<button type="button" onClick={()=>onSelect(tenant)} aria-label={`View details for ${name}`}>{content}</button>:content}</article>})}</div>; }
export function ContentCards({ resource }) { const [items,loading]=useContent(resource); if (loading) return <Loading/>; return <div className="content-grid">{items.map(item => <article key={item.id}>{item.cover_image_url && <img src={assetUrl(item.cover_image_url)} alt={item.title||item.name||""} loading="lazy" decoding="async"/>}<span>{item.space_type||item.venue||item.location_detail||item.status}</span><h3>{item.title||item.name}</h3><p>{item.summary||item.description}</p>{item.action_url && <a className="text-link card-action" href={item.action_url} target="_blank" rel="noreferrer">{item.action_label||"Learn more"} &rarr;</a>}</article>)}</div>; }

export function HoursStrip() {
  const [hours] = useContent("mall_hours"); const settings=useSettings(),[now,setNow]=useState(()=>new Date());
  useEffect(()=>{const timer=setInterval(()=>setNow(new Date()),1000);return()=>clearInterval(timer)},[]);
  const timeZone="Asia/Manila",weekdayName=new Intl.DateTimeFormat("en-US",{timeZone,weekday:"long"}).format(now),weekdays=["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"],dayIndex=weekdays.indexOf(weekdayName),today=hours.find(h=>+h.day_of_week===dayIndex);
  const parts=Object.fromEntries(new Intl.DateTimeFormat("en-US",{timeZone,hour:"2-digit",minute:"2-digit",second:"2-digit",hourCycle:"h23"}).formatToParts(now).map(part=>[part.type,part.value])),minutes=Number(parts.hour)*60+Number(parts.minute),opening=today?+today.opening_time.slice(0,2)*60:0,closing=today?+today.closing_time.slice(0,2)*60:0;
  const open=today&&!today.is_closed&&minutes>=opening&&minutes<closing,liveDate=new Intl.DateTimeFormat("en-PH",{timeZone,weekday:"long",month:"long",day:"numeric",year:"numeric"}).format(now),liveTime=new Intl.DateTimeFormat("en-PH",{timeZone,hour:"numeric",minute:"2-digit",second:"2-digit",hour12:true}).format(now);
  return <section className="hours-strip"><div><span>Mall hours</span><strong>{settings["hours.title"]||"Open daily for shopping, dining, services, and entertainment."}</strong><p>{settings["hours.schedule"]||"10:00 AM–9:00 PM Monday–Thursday · 9:00 AM–9:00 PM Friday–Sunday"}</p></div><div><span>Mall status</span><strong>{open?"Open now":"Closed"}</strong><time className="mall-live-time" dateTime={now.toISOString()}><b>{liveTime}</b><small>{liveDate} · Philippine Time</small></time></div></section>;
}

export function MediaFeature({ item }) {
  const images=typeof item.images==="string"?JSON.parse(item.images):item.images||[]; const [active,setActive]=useState(0);
  useEffect(()=>{if(window.matchMedia('(prefers-reduced-motion: reduce)').matches)return;const timer=setInterval(()=>setActive(i=>(i+1)%Math.max(images.length,1)),4500);return()=>clearInterval(timer)},[images.length]);
  useEffect(()=>{if(images.length>1){const preload=new Image();preload.src=assetUrl(images[(active+1)%images.length])}},[active,images]);
  return <section className="media-feature" aria-roledescription="carousel" aria-label={item.title}><div className="media-stage" aria-live="polite">{images[active]&&<img key={images[active]} className="active" src={assetUrl(images[active])} alt={`${item.title}, image ${active+1} of ${images.length}`} decoding="async"/>}<button type="button" className="slide prev" aria-label="Previous image" onClick={()=>setActive((active-1+images.length)%images.length)}>&lsaquo;</button><button type="button" className="slide next" aria-label="Next image" onClick={()=>setActive((active+1)%images.length)}>&rsaquo;</button><div className="dots">{images.map((_,i)=><button type="button" aria-label={`Show image ${i+1}`} aria-current={i===active?"true":undefined} key={i} className={i===active?"active":""} onClick={()=>setActive(i)}/>)}</div></div><div className="media-copy"><p className="eyebrow">{item.eyebrow}</p><h2>{item.title}</h2><p>{item.description}</p><a className="text-link" href={item.button_url}>{item.button_text}</a></div></section>;
}

export function HighlightsCarousel({ items }) {
  const [active,setActive]=useState(0); if(!items.length)return <Loading/>; const show=index=>setActive((index+items.length)%items.length);
  return <section className="highlights-carousel" aria-label="Featured destinations"><div className="highlights-viewport"><MediaFeature key={items[active].id} item={items[active]}/></div><button type="button" aria-label="Previous feature" className="feature-arrow feature-prev" onClick={()=>show(active-1)}>&lsaquo;</button><button type="button" aria-label="Next feature" className="feature-arrow feature-next" onClick={()=>show(active+1)}>&rsaquo;</button><div className="feature-indicators">{items.map((item,index)=><button type="button" aria-label={`Show ${item.title}`} aria-current={index===active?"true":undefined} key={item.id} className={index===active?"active":""} onClick={()=>show(index)}/>)}</div></section>;
}
