import { useEffect, useState } from "react";
import { Link, NavLink, Navigate, useNavigate, useParams } from "react-router-dom";
import { Image, LayoutDashboard, LogOut, Upload } from "lucide-react";
import { api } from "../api";
import { adminFields, adminResources } from "../config/site";
import { Loading } from "../components/content/ContentComponents";

const cacheKey=resource=>`icm_admin_resource_${resource}`;
function readCache(resource){try{return JSON.parse(sessionStorage.getItem(cacheKey(resource)))||null}catch{return null}}
function writeCache(resource,rows){sessionStorage.setItem(cacheKey(resource),JSON.stringify(rows))}

function ConfirmDialog({open,title,message,confirmLabel="Delete",busy=false,onConfirm,onCancel}){useEffect(()=>{if(!open)return;const close=event=>event.key==="Escape"&&!busy&&onCancel();document.addEventListener("keydown",close);return()=>document.removeEventListener("keydown",close)},[open,busy,onCancel]);if(!open)return null;return <div className="admin-dialog-backdrop" role="presentation" onMouseDown={event=>event.target===event.currentTarget&&!busy&&onCancel()}><section className="admin-dialog" role="alertdialog" aria-modal="true" aria-labelledby="admin-dialog-title" aria-describedby="admin-dialog-message"><div className="admin-dialog-icon">!</div><h2 id="admin-dialog-title">{title}</h2><p id="admin-dialog-message">{message}</p><div><button type="button" onClick={onCancel} disabled={busy}>Cancel</button><button type="button" className="admin-dialog-danger" onClick={onConfirm} disabled={busy} autoFocus>{busy?"Deleting...":confirmLabel}</button></div></section></div>}
function AdminNotice({message,type="success",onClose}){useEffect(()=>{if(!message||type==="error")return;const timer=setTimeout(onClose,4500);return()=>clearTimeout(timer)},[message,type,onClose]);if(!message)return null;return <div className={`admin-notice ${type}`} role={type==="error"?"alert":"status"}><span>{message}</span><button type="button" aria-label="Dismiss notification" onClick={onClose}>&times;</button></div>}

export function AdminGuard({children}){return localStorage.getItem("icm_admin_token")?children:<Navigate to="/admin" replace/>}

export function AdminLoginPage(){
  const navigate=useNavigate(); const [error,setError]=useState(""),[challenge,setChallenge]=useState(null),[submitting,setSubmitting]=useState(false),[otp,setOtp]=useState(""),[resendIn,setResendIn]=useState(0);
  useEffect(()=>{if(resendIn<=0)return;const timer=setInterval(()=>setResendIn(value=>Math.max(0,value-1)),1000);return()=>clearInterval(timer)},[resendIn]);
  async function login(event){event.preventDefault();setError("");setSubmitting(true);try{const result=await api("/admin/login",{method:"POST",body:JSON.stringify(Object.fromEntries(new FormData(event.currentTarget)))});setChallenge(result.challenge_id);setResendIn(result.resend_after||60)}catch(exception){setError(exception.message)}finally{setSubmitting(false)}}
  async function verify(event){event.preventDefault();setError("");setSubmitting(true);if(otp.length!==6){setError("Enter the six-digit code sent to your Gmail account.");setSubmitting(false);return}try{const result=await api("/admin/verify-otp",{method:"POST",body:JSON.stringify({challenge_id:challenge,code:otp})});localStorage.setItem("icm_admin_token",result.token);navigate("/admin/dashboard")}catch(exception){setError(exception.message)}finally{setSubmitting(false)}}
  async function resend(){setSubmitting(true);setError("");try{const result=await api("/admin/resend-otp",{method:"POST",body:JSON.stringify({challenge_id:challenge})});setChallenge(result.challenge_id);setOtp("");setResendIn(result.resend_after||60)}catch(e){setError(e.message)}finally{setSubmitting(false)}}
  return <main className="login"><form onSubmit={challenge?verify:login} noValidate={Boolean(challenge)}><img src="/images/general_images/icm_logo_transparent.png" alt="Island Central Mactan"/><h1>{challenge?"Verify your login":"Admin portal"}</h1>{challenge?<><p className="login-note">A six-digit code was sent to the administrator Gmail account. It expires in 10 minutes.</p><label>One-time code<input className="otp-input" name="code" type="text" inputMode="numeric" autoComplete="one-time-code" value={otp} onChange={event=>{setOtp(event.target.value.replace(/\D/g,"").slice(0,6));setError("")}} required autoFocus/></label><small className="otp-help">Enter exactly 6 digits. This is the emailed verification code, not your admin password.</small></>:<><label>Email<input name="email" type="email" autoComplete="username" required/></label><label>Password<input name="password" type="password" autoComplete="current-password" required/></label></>}{error&&<p className="error" role="alert">{error}</p>}<button className="button" disabled={submitting||(challenge&&otp.length!==6)}>{submitting?"Please wait...":challenge?"Verify code":"Continue"}</button>{challenge&&<><button className="login-back" type="button" disabled={submitting||resendIn>0} onClick={resend}>{resendIn>0?`Resend code in ${resendIn}s`:"Resend code"}</button><button className="login-back" type="button" onClick={()=>{setChallenge(null);setOtp("");setError("")}}>Use a different login</button></>}</form></main>;
}

export function AdminShell({children}){const navigate=useNavigate();function logout(){api("/admin/logout",{method:"POST"}).finally(()=>{localStorage.removeItem("icm_admin_token");sessionStorage.clear();navigate("/admin")})}return <div className="admin"><aside><img src="/images/general_images/icm_logo_transparent.png" alt=""/><NavLink to="/admin/dashboard"><LayoutDashboard/>Overview</NavLink>{adminResources.map(([key,label,Icon])=><NavLink key={key} to={`/admin/manage/${key}`}><Icon/>{label}</NavLink>)}<button onClick={logout}><LogOut/>Log out</button></aside><section className="admin-main">{children}</section></div>}
export function AdminDashboardPage(){
  useEffect(()=>{const timer=setTimeout(()=>adminResources.slice(0,6).forEach(([resource])=>{if(!readCache(resource))api(`/admin/${resource}`).then(result=>writeCache(resource,result.data)).catch(()=>{})}),250);return()=>clearTimeout(timer)},[]);
  return <AdminGuard><AdminShell><p className="eyebrow">Content management</p><h1>Dashboard</h1><div className="feature-grid">{adminResources.slice(0,6).map(([key,label,Icon])=><Link className="feature" key={key} to={`/admin/manage/${key}`}><i><Icon/></i><h3>{label}</h3></Link>)}</div><PasswordForm/></AdminShell></AdminGuard>;
}

function PasswordForm(){const [message,setMessage]=useState(""),[error,setError]=useState(""),[saving,setSaving]=useState(false);async function submit(event){event.preventDefault();setSaving(true);setError("");setMessage("");try{const result=await api("/admin/change-password",{method:"POST",body:JSON.stringify(Object.fromEntries(new FormData(event.currentTarget)))});setMessage(result.message);event.currentTarget.reset()}catch(e){setError(e.message)}finally{setSaving(false)}}return <form className="password-form" onSubmit={submit}><p className="eyebrow">Account security</p><h2>Change administrator password</h2><p>Use at least 12 characters with uppercase, lowercase, a number, and a symbol.</p><div><label>Current password<input type="password" name="current_password" autoComplete="current-password" required/></label><label>New password<input type="password" name="password" autoComplete="new-password" minLength="12" required/></label><label>Confirm new password<input type="password" name="password_confirmation" autoComplete="new-password" minLength="12" required/></label></div>{error&&<p className="error" role="alert">{error}</p>}{message&&<p className="success" role="status">{message}</p>}<button className="button" disabled={saving}>{saving?"Updating...":"Update password"}</button></form>}

export function AdminResourcePage(){const {resource}=useParams();return resource==="media"?<MediaLibraryPage/>:<StandardAdminResourcePage resource={resource}/>}
function StandardAdminResourcePage({resource}){
  const cached=readCache(resource);
  const [rows,setRows]=useState(cached||[]),[editing,setEditing]=useState(null),[error,setError]=useState(""),[notice,setNotice]=useState(""),[pendingDelete,setPendingDelete]=useState(null),[deleting,setDeleting]=useState(false);
  const [loading,setLoading]=useState(!cached),[refreshing,setRefreshing]=useState(Boolean(cached)),[saving,setSaving]=useState(false),[page,setPage]=useState(1),[lastPage,setLastPage]=useState(1),[query,setQuery]=useState(""),[searchInput,setSearchInput]=useState("");
  const label=adminResources.find(item=>item[0]===resource)?.[1]||resource;

  useEffect(()=>{let active=true;const existing=page===1&&!query?readCache(resource):null;setRows(existing||[]);setLoading(!existing);setRefreshing(Boolean(existing));setError("");setEditing(null);api(`/admin/${resource}?page=${page}${query?`&search=${encodeURIComponent(query)}`:""}`).then(result=>{if(active){setRows(result.data);setLastPage(result.last_page||1);if(page===1&&!query)writeCache(resource,result.data)}}).catch(exception=>active&&setError(exception.message)).finally(()=>{if(active){setLoading(false);setRefreshing(false)}});return()=>{active=false}},[resource,page,query]);
  function commit(next){setRows(next);writeCache(resource,next)}
  async function save(event){event.preventDefault();setSaving(true);setError("");const payload=Object.fromEntries([...new FormData(event.currentTarget)].filter(([,value])=>value!==""));try{const saved=await api(`/admin/${resource}${editing?.id?`/${editing.id}`:""}`,{method:editing?.id?"PUT":"POST",body:JSON.stringify(payload)});commit(editing?.id?rows.map(row=>row.id===saved.id?saved:row):[saved,...rows]);setEditing(null);setNotice(`Record ${editing?.id?"updated":"created"} successfully.`)}catch(exception){setError(exception.message)}finally{setSaving(false)}}
  async function remove(){if(!pendingDelete)return;const previous=rows,id=pendingDelete.id;setDeleting(true);commit(rows.filter(row=>row.id!==id));try{await api(`/admin/${resource}/${id}`,{method:"DELETE"});setPendingDelete(null);setNotice("Record deleted successfully.")}catch(exception){commit(previous);setError(exception.message);setPendingDelete(null)}finally{setDeleting(false)}}

  return <AdminGuard><AdminShell><AdminNotice message={notice} onClose={()=>setNotice("")}/><div className="admin-title"><div><h1>{label}</h1>{refreshing&&<span className="admin-refreshing">Refreshing...</span>}</div>{resource!=="inquiries"&&<button className="button" onClick={()=>setEditing({})}>Add record</button>}</div><form className="admin-search" onSubmit={event=>{event.preventDefault();setPage(1);setQuery(searchInput)}}><input value={searchInput} onChange={event=>setSearchInput(event.target.value)} placeholder={`Search ${label.toLowerCase()}`}/><button>Search</button></form>{error&&<AdminNotice message={error} type="error" onClose={()=>setError("")}/>}<div className={`table${loading?" admin-table-loading":""}`}>{loading?Array.from({length:6},(_,index)=><div className="table-row admin-skeleton" key={index}><div><i/><small/></div></div>):rows.map(row=><div className="table-row" key={row.id}><div><strong>{row.name||row.title||row.reference_number||row.key}</strong><small>{row.status||row.value}</small></div><div><button onClick={()=>setEditing(row)}>Edit</button>{resource!=="inquiries"&&<button className="danger" onClick={()=>setPendingDelete(row)}>Delete</button>}</div></div>)}</div><div className="admin-pagination"><button disabled={page<=1} onClick={()=>setPage(value=>value-1)}>Previous</button><span>Page {page} of {lastPage}</span><button disabled={page>=lastPage} onClick={()=>setPage(value=>value+1)}>Next</button></div>{editing&&<div className="modal"><form onSubmit={save}><h2>{editing.id?"Edit":"Add"} {label}</h2>{(adminFields[resource]||[]).map(field=><label key={field}>{field.replaceAll("_"," ")}{["description","summary","internal_notes","value"].includes(field)?<textarea name={field} defaultValue={editing[field]||""}/>:<input name={field} defaultValue={editing[field]||""}/>}</label>)}<div><button type="button" onClick={()=>setEditing(null)}>Cancel</button><button className="button" disabled={saving}>{saving?"Saving...":"Save"}</button></div></form></div>}<ConfirmDialog open={Boolean(pendingDelete)} title="Delete this record?" message={`${pendingDelete?.name||pendingDelete?.title||pendingDelete?.key||"This record"} will be removed from the system. This action cannot be undone.`} busy={deleting} onCancel={()=>setPendingDelete(null)} onConfirm={remove}/></AdminShell></AdminGuard>;
}

function MediaLibraryPage(){
  const [items,setItems]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[notice,setNotice]=useState(""),[uploading,setUploading]=useState(false),[query,setQuery]=useState(""),[pendingDelete,setPendingDelete]=useState(null),[deleting,setDeleting]=useState(false);
  async function load(search=""){setLoading(true);try{const result=await api(`/admin/media?per_page=60${search?`&search=${encodeURIComponent(search)}`:""}`);setItems(result.data)}catch(e){setError(e.message)}finally{setLoading(false)}}
  useEffect(()=>{load()},[]);
  async function upload(event){event.preventDefault();setUploading(true);setError("");try{const form=new FormData(event.currentTarget);const saved=await api("/admin/media",{method:"POST",body:form});setItems(current=>[saved,...current]);event.currentTarget.reset();setNotice("Image uploaded successfully.")}catch(e){setError(e.message)}finally{setUploading(false)}}
  async function remove(){if(!pendingDelete)return;setDeleting(true);try{await api(`/admin/media/${pendingDelete.id}`,{method:"DELETE"});setItems(current=>current.filter(x=>x.id!==pendingDelete.id));setPendingDelete(null);setNotice("Image deleted successfully.")}catch(e){setError(e.message);setPendingDelete(null)}finally{setDeleting(false)}}
  async function copyUrl(url){try{await navigator.clipboard.writeText(url);setNotice("Image URL copied to the clipboard.")}catch{setError("The image URL could not be copied. Please copy it manually.")}}
  return <AdminGuard><AdminShell><AdminNotice message={notice} onClose={()=>setNotice("")}/>{error&&<AdminNotice message={error} type="error" onClose={()=>setError("")}/>}<div className="admin-title"><div><p className="eyebrow">Reusable assets</p><h1>Media library</h1></div></div><form className="media-upload" onSubmit={upload}><label><Upload/>Choose image<input name="file" type="file" accept="image/jpeg,image/png,image/webp,image/avif,image/gif" required/></label><input name="alt_text" placeholder="Descriptive alternative text" maxLength="255"/><button className="button" disabled={uploading}>{uploading?"Uploading...":"Upload image"}</button></form><form className="admin-search" onSubmit={e=>{e.preventDefault();load(query)}}><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search media"/><button>Search</button></form>{loading?<Loading/>:<div className="media-grid">{items.map(item=><article key={item.id}><img src={item.url} alt={item.alt_text||item.name} loading="lazy"/><div><strong>{item.name}</strong><small>{item.width&&item.height?`${item.width} × ${item.height} · `:""}{Math.ceil(item.size_bytes/1024)} KB</small><button type="button" onClick={()=>copyUrl(item.url)}>Copy URL</button><button className="danger" type="button" onClick={()=>setPendingDelete(item)}>Delete</button></div></article>)}{!items.length&&<div className="admin-empty"><Image/><p>No images found.</p></div>}</div>}<ConfirmDialog open={Boolean(pendingDelete)} title="Delete this image?" message={`${pendingDelete?.name||"This image"} will be permanently removed from the media library.`} busy={deleting} onCancel={()=>setPendingDelete(null)} onConfirm={remove}/></AdminShell></AdminGuard>}
