import { useState } from "react";
import { Link } from "react-router-dom";
import { Building2, CalendarDays, Search, Send, Store } from "lucide-react";
import { api } from "../api";
import { SiteLayout } from "../components/layout/SiteLayout";
import { ContentCards, Feature, HighlightsCarousel, HoursStrip, Loading, MediaFeature, PageHero, TenantGrid } from "../components/content/ContentComponents";
import { useContent, useSettings } from "../hooks/useContent";
import { assetUrl } from "../config/site";

export function HomePage(){const [featured,loading]=useContent("tenants?featured=1"),[highlights]=useContent("highlights"),settings=useSettings();return <SiteLayout variant="home"><main><section className="hero home-hero"><img src={assetUrl(settings["home.background_url"]||"images/general_images/icm.png")} alt="Island Central Mactan mall facade" fetchPriority="high"/><div className="home-hero-content"><span>{settings["home.eyebrow"]||"Island Central Mactan"}</span><h1>{settings["home.title"]||"More than just a mall, it's living the island life."}</h1><p>{settings["home.description"]}</p><div className="hero-buttons"><Link className="button hero-primary" to={settings["home.primary_url"]||"/leasing"}>{settings["home.primary_label"]||"View Leasing"}</Link><Link className="button outline hero-secondary" to={settings["home.secondary_url"]||"/mall"}>{settings["home.secondary_label"]||"Explore the Mall"}</Link></div></div><a className="hero-scroll-cue" href="#home-discover" aria-label="Continue to mall information"><span>Discover</span><i/></a></section><HoursStrip/><section className="section" id="home-discover"><p className="eyebrow">Welcome</p><h2>A complete destination for shoppers, tenants, and the Mactan community.</h2><HighlightsCarousel items={highlights.slice(0,2)}/><div className="feature-grid"><Feature icon={<Store/>} title="Tenant directory" text="Find stores, restaurants and services." to="/directory"/><Feature icon={<Building2/>} title="Leasing opportunities" text="Discover spaces prepared for growing brands." to="/leasing"/><Feature icon={<CalendarDays/>} title="What's happening" text="See upcoming events and promotions." to="/events"/></div>{!loading&&featured.length>0&&<TenantGrid tenants={featured}/>}</section></main></SiteLayout>}

export function DirectoryPage(){const [tenants,loading]=useContent("tenants"),[query,setQuery]=useState(""),settings=useSettings();const shown=tenants.filter(t=>`${t.name} ${t.location_detail}`.toLowerCase().includes(query.toLowerCase()));return <SiteLayout><main><PageHero variant="directory" eyebrow={settings["directory.eyebrow"]} title={settings["directory.title"]||"Mall directory"} text={settings["directory.description"]} backgroundUrl={settings["directory.background_url"]}/><section className="section"><label className="search"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search tenants or locations"/></label>{loading?<Loading/>:<><p aria-live="polite">{shown.length} tenants found</p><TenantGrid tenants={shown}/></>}</section></main></SiteLayout>}

export function MallPage(){const [tenants]=useContent("tenants"),[highlights]=useContent("highlights"),[events]=useContent("events"),settings=useSettings(),gallery=highlights.find(x=>x.slug==="mall-gallery");return <SiteLayout><main><PageHero variant="mall" eyebrow={settings["mall.eyebrow"]||"Shop & Dine"} title={settings["mall.title"]||"Everything you need, all in one place."} text={settings["mall.description"]} backgroundUrl={settings["mall.background_url"]}><div className="mall-hero-actions"><Link className="button mall-hero-primary" to="/directory">Browse Stores &amp; Restaurants</Link><Link className="button outline mall-hero-secondary" to="/leasing">Retail Leasing</Link></div></PageHero><section className="stats"><article><span>Dining</span><strong>Restaurants, cafes and quick bites</strong></article><article><span>Essentials</span><strong>Groceries, errands and services</strong></article><article><span>Leisure</span><strong>Cinema, family stops and events</strong></article></section><section className="section">{gallery&&<MediaFeature item={gallery}/>}<h2>Brands people already know.</h2><TenantGrid tenants={tenants.filter(x=>x.logo_url).slice(0,8)}/><h2>Happening at Island Central</h2><div className="content-grid">{events.slice(0,3).map(x=><article key={x.id}><img src={assetUrl(x.cover_image_url)} alt={x.title} loading="lazy" decoding="async"/><span>{x.venue}</span><h3>{x.title}</h3><p>{x.summary}</p></article>)}</div></section></main></SiteLayout>}

export function LeasingPage(){const [spaces,loading]=useContent("leasing_spaces"),[type,setType]=useState("All"),[query,setQuery]=useState(""),settings=useSettings();const shown=spaces.filter(x=>(type==="All"||x.space_type===type)&&x.title.toLowerCase().includes(query.toLowerCase()));return <SiteLayout><main><PageHero variant="leasing" eyebrow={settings["leasing.eyebrow"]||"Leasing Opportunities"} title={settings["leasing.title"]||"Put your brand where Mactan moves daily."} text={settings["leasing.description"]} backgroundUrl={settings["leasing.background_url"]}><a className="button outline leasing-hero-action" href="#available-spaces">View Available Spaces</a></PageHero><section className="section" id="available-spaces"><p className="eyebrow">Available Spaces</p><h2>Lease-ready opportunities for brands ready to grow.</h2><div className="space-toolbar"><div>{["All","Retail","Dining","Service"].map(x=><button type="button" className={type===x?"active":""} onClick={()=>setType(x)} key={x}>{x}</button>)}</div><label className="search"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search spaces"/></label></div>{loading?<Loading/>:<div className="space-list">{shown.map(x=><article key={x.id}><img src={assetUrl(x.cover_image_url)} alt={x.title} loading="lazy" decoding="async"/><div><span className="eyebrow">{x.space_type} &middot; {x.availability_status}</span><h2>{x.title}</h2><p>{x.description}</p></div><Link className="button" to="/inquire">Inquire</Link></article>)}</div>}</section></main></SiteLayout>}

export function EventsPage(){const settings=useSettings();return <SiteLayout><main><PageHero variant="events" eyebrow={settings["events.eyebrow"]} title={settings["events.title"]||"Events & Promos"} text={settings["events.description"]} backgroundUrl={settings["events.background_url"]}/><section className="section"><ContentCards resource="events"/><h2>Current promotions</h2><ContentCards resource="promotions"/></section></main></SiteLayout>}
export function ServicesPage(){const settings=useSettings();return <SiteLayout><main><PageHero variant="services" eyebrow={settings["services.eyebrow"]||"Services"} title={settings["services.title"]||"Mall services"} text={settings["services.description"]} backgroundUrl={settings["services.background_url"]}/><section className="section"><ContentCards resource="services"/></section></main></SiteLayout>}

export function AboutPage(){const settings=useSettings();return <SiteLayout><main><PageHero variant="about" eyebrow={settings["about.eyebrow"]} title={settings["about.title"]||"More than a mall in the heart of Mactan."} text={settings["about.introduction"]} backgroundUrl={settings["about.background_url"]}/><section className="section about-story"><div><p className="eyebrow">Our Story</p><h2>An accessible island destination built for everyday life.</h2><p>{settings["about.story"]||settings["about.introduction"]}</p></div><img src="/images/general_images/employees.webp" alt="Island Central Mactan team" loading="lazy" decoding="async"/><div className="about-facts"><article><strong>2013</strong><span>Founded</span></article><article><strong>2016</strong><span>Mall operations began</span></article><article><strong>100+</strong><span>Tenants</span></article><article><strong>400</strong><span>Parking slots</span></article></div><div className="about-details"><article><span>Accessible by design</span><p>{settings["about.accessibility"]}</p></article><article><span>A mixed-use destination</span><p>{settings["about.development"]}</p></article></div><div className="values-grid"><article><span>Mission</span><p>{settings["about.mission"]}</p></article><article><span>Vision</span><p>{settings["about.vision"]}</p></article></div></section></main></SiteLayout>}

function LocationSection(){const settings=useSettings();return <section className="section location-section"><div className="location-copy"><p className="eyebrow">Visit Us</p><h2>{settings["location.title"]||"Visit Island Central Mactan."}</h2><p>{settings["location.description"]}</p><div className="location-details"><article><strong>By Car</strong><p>Accessible from major roads with convenient parking.</p></article><article><strong>Nearby Landmarks</strong><p>{settings["location.landmark"]||"Across Mactan-Cebu International Airport."}</p></article></div></div><div className="map-panel"><iframe title="Island Central Mactan location" src={settings["contact.maps_embed_url"]} loading="lazy" referrerPolicy="no-referrer-when-downgrade" allowFullScreen/><a className="button map-button" href={settings["contact.maps_directions_url"]} target="_blank" rel="noreferrer">Open in Google Maps</a></div></section>}
export function InquirePage(){const [done,setDone]=useState(""),[error,setError]=useState(""),settings=useSettings();async function submit(event){event.preventDefault();try{const result=await api("/inquiries",{method:"POST",body:JSON.stringify(Object.fromEntries(new FormData(event.currentTarget)))});setDone(result.reference_number)}catch(exception){setError(exception.message)}}return <SiteLayout><main><PageHero variant="inquire" eyebrow={settings["inquire.eyebrow"]} title={settings["inquire.title"]||"Let's connect"} text={settings["inquire.description"]} backgroundUrl={settings["inquire.background_url"]}/><section className="section narrow">{done?<div className="success"><h2>Inquiry received</h2><p>Reference: <strong>{done}</strong></p></div>:<form className="form" onSubmit={submit}><label>Full name<input name="name" required/></label><label>Email<input name="email" type="email" required/></label><label>Phone<input name="phone"/></label><label>Inquiry type<select name="inquiry_type" required><option value="">Select one</option><option>Leasing</option><option>Marketing collaboration</option><option>Events</option><option>Mall services</option><option>General inquiry</option></select></label><label>Message<textarea name="message" rows="6" required/></label>{error&&<p className="error" role="alert">{error}</p>}<button className="button"><Send size={18}/> Submit inquiry</button></form>}</section><LocationSection/></main></SiteLayout>}

export function PolicyPage({type}){const content={"privacy-policy":["Privacy Policy","We respect your privacy and handle personal information only for legitimate mall, leasing, and inquiry purposes."],"terms-of-service":["Terms of Service","Use of this website is subject to applicable laws and the published policies of Island Central Mactan."],"cookies-policy":["Cookies Policy","This website may use necessary browser storage to support authentication and improve your experience."]}[type];return <SiteLayout><main><PageHero variant="about" title={content[0]} text="Island Central Mactan website policy"/><section className="section narrow"><h2>{content[0]}</h2><p>{content[1]}</p></section></main></SiteLayout>}
